version: "3.2"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./front
        target: /rails-api-and-vuecli/front
      - type: volume
        source: node-modules-data
        target: /rails-api-and-vuecli/front/node_modules
    stdin_open: true
    tty: true

  ruby:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    container_name: ruby
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: rails_user
      DATABASE_PASSWORD: password
    volumes:
      - type: bind
        source: ./
        target: /rails-api-and-vuecli
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres:12.4-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rails_user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80

volumes:
  node-modules-data:
  postgres-data:
