version: "3.2"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node
    command: sh -c "npm install && npm run serve"
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./front
        target: /rails-api-and-vuecli/front
      - type: volume
        source: node-modules-data
        target: /rails-api-and-vuecli/front/node_modules
    stdin_open: true
    tty: true

  ruby:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    container_name: ruby
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./
        target: /rails-api-and-vuecli
    stdin_open: true
    tty: true


volumes:
  node-modules-data:
